<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Config</string>
	</array>
	<key>foldingStartMarker</key>
	<string>[{(]\s*$</string>
	<key>foldingStopMarker</key>
	<string>[})];</string>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>Brazil Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section-value</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#name-value</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.brazil-config</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.brazil-config</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.array.brazil-config</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.brazil-config</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.brazil-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.brazil-config</string>
		</dict>
		<key>dictionary</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.brazil-config</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.brazil-config</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.dictionary.brazil-config</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#name-value</string>
				</dict>
			</array>
		</dict>
		<key>name-value</key>
		<dict>
			<key>begin</key>
			<string>\s*([^=#]+)\s*=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.attribute-name.brazil-config</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.semi-colon.brazil-config</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>-?\d+(?:.\d+)?\s*(?=;)</string>
			<key>name</key>
			<string>constant.numeric.brazil-config</string>
		</dict>
		<key>section-value</key>
		<dict>
			<key>begin</key>
			<string>(([^.]+)\.([^.]+)\.(?:[^\s+=]+))\s*\+?=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.brazil-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.section.domain.brazil-config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.section.realm.brazil-config</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Top level section definition.</string>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.semi-colon.brazil-config</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.brazil-config</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.brazil-config</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.brazil-config</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\"</string>
					<key>name</key>
					<string>constant.character.escape.brazil-config</string>
				</dict>
			</array>
		</dict>
		<key>unquoted-string</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.brazil-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^;{()}",#]+)</string>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#white-space</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dictionary</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unquoted-string</string>
				</dict>
			</array>
		</dict>
		<key>white-space</key>
		<dict>
			<key>match</key>
			<string>\s+</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.brazil-config</string>
	<key>uuid</key>
	<string>C8A7C39D-F3F5-42BC-8CB8-94FCA99B0B18</string>
</dict>
</plist>
